import vscode from 'vscode';

// TODO
const VSCODE_MODULE: typeof vscode = {
    version: vscode.version,
    // namespaces
    authentication,
    commands,
    comments,
    debug,
    env,
    extensions,
    l10n,
    languages,
    notebooks,
    scm,
    tasks,
    tests,
    window,
    workspace,
    // types
    Position: undefined,
    Range: undefined,
    Selection: undefined,
    TextEditorSelectionChangeKind: undefined,
    TextEditorCursorStyle: undefined,
    TextEditorLineNumbersStyle: undefined,
    TextEditorRevealType: undefined,
    OverviewRulerLane: undefined,
    DecorationRangeBehavior: undefined,
    ThemeColor: undefined,
    ThemeIcon: undefined,
    EndOfLine: undefined,
    Uri: undefined,
    CancellationTokenSource: undefined,
    CancellationError: undefined,
    Disposable: undefined,
    EventEmitter: undefined,
    QuickPickItemKind: undefined,
    InputBoxValidationSeverity: undefined,
    RelativePattern: undefined,
    CodeActionKind: undefined,
    CodeActionTriggerKind: undefined,
    CodeAction: undefined,
    CodeLens: undefined,
    MarkdownString: undefined,
    Hover: undefined,
    EvaluatableExpression: undefined,
    InlineValueText: undefined,
    InlineValueVariableLookup: undefined,
    InlineValueEvaluatableExpression: undefined,
    DocumentHighlightKind: undefined,
    DocumentHighlight: undefined,
    SymbolKind: undefined,
    SymbolTag: undefined,
    SymbolInformation: undefined,
    DocumentSymbol: undefined,
    TextEdit: undefined,
    SnippetTextEdit: undefined,
    NotebookEdit: undefined,
    WorkspaceEdit: undefined,
    SnippetString: undefined,
    SemanticTokensLegend: undefined,
    SemanticTokensBuilder: undefined,
    SemanticTokens: undefined,
    SemanticTokensEdits: undefined,
    SemanticTokensEdit: undefined,
    ParameterInformation: undefined,
    SignatureInformation: undefined,
    SignatureHelp: undefined,
    SignatureHelpTriggerKind: undefined,
    CompletionItemKind: undefined,
    CompletionItemTag: undefined,
    CompletionItem: undefined,
    CompletionList: undefined,
    CompletionTriggerKind: undefined,
    InlineCompletionList: undefined,
    InlineCompletionTriggerKind: undefined,
    InlineCompletionItem: undefined,
    DocumentLink: undefined,
    Color: undefined,
    ColorInformation: undefined,
    ColorPresentation: undefined,
    InlayHintKind: undefined,
    InlayHintLabelPart: undefined,
    InlayHint: undefined,
    FoldingRange: undefined,
    FoldingRangeKind: undefined,
    SelectionRange: undefined,
    CallHierarchyItem: undefined,
    CallHierarchyIncomingCall: undefined,
    CallHierarchyOutgoingCall: undefined,
    TypeHierarchyItem: undefined,
    LinkedEditingRanges: undefined,
    DocumentDropEdit: undefined,
    IndentAction: undefined,
    ConfigurationTarget: undefined,
    Location: undefined,
    DiagnosticSeverity: undefined,
    DiagnosticRelatedInformation: undefined,
    DiagnosticTag: undefined,
    Diagnostic: undefined,
    LanguageStatusSeverity: undefined,
    ViewColumn: undefined,
    StatusBarAlignment: undefined,
    TerminalLocation: undefined,
    TerminalLink: undefined,
    TerminalProfile: undefined,
    FileDecoration: undefined,
    ExtensionKind: undefined,
    ExtensionMode: undefined,
    ColorThemeKind: undefined,
    TaskRevealKind: undefined,
    TaskPanelKind: undefined,
    TaskGroup: undefined,
    ProcessExecution: undefined,
    ShellQuoting: undefined,
    ShellExecution: undefined,
    CustomExecution: undefined,
    TaskScope: undefined,
    Task: undefined,
    tasks: undefined,
    FileType: undefined,
    FilePermission: undefined,
    FileSystemError: undefined,
    FileChangeType: undefined,
    UIKind: undefined,
    LogLevel: undefined,
    env: undefined,
    window: undefined,
    DataTransferItem: undefined,
    DataTransfer: undefined,
    TreeItem: undefined,
    TreeItemCollapsibleState: undefined,
    TerminalExitReason: undefined,
    EnvironmentVariableMutatorType: undefined,
    ProgressLocation: undefined,
    QuickInputButtons: undefined,
    TextDocumentChangeReason: undefined,
    TextDocumentSaveReason: undefined,
    workspace: undefined,
    languages: undefined,
    NotebookEditorRevealType: undefined,
    NotebookCellKind: undefined,
    NotebookRange: undefined,
    NotebookCellOutputItem: undefined,
    NotebookCellOutput: undefined,
    NotebookCellData: undefined,
    NotebookData: undefined,
    NotebookControllerAffinity: undefined,
    NotebookCellStatusBarAlignment: undefined,
    NotebookCellStatusBarItem: undefined,
    notebooks: undefined,
    scm: undefined,
    DebugAdapterExecutable: undefined,
    DebugAdapterServer: undefined,
    DebugAdapterNamedPipeServer: undefined,
    DebugAdapterInlineImplementation: undefined,
    Breakpoint: undefined,
    SourceBreakpoint: undefined,
    FunctionBreakpoint: undefined,
    DebugConsoleMode: undefined,
    DebugConfigurationProviderTriggerKind: undefined,
    debug: undefined,
    extensions: undefined,
    CommentThreadCollapsibleState: undefined,
    CommentMode: undefined,
    comments: undefined,
    authentication: undefined,
    l10n: undefined,
    tests: undefined,
    TestRunProfileKind: undefined,
    TestTag: undefined,
    TestRunRequest: undefined,
    TestMessage: undefined,
    TabInputText: undefined,
    TabInputTextDiff: undefined,
    TabInputCustom: undefined,
    TabInputWebview: undefined,
    TabInputNotebook: undefined,
    TabInputNotebookDiff: undefined,
    TabInputTerminal: undefined
}

export default VSCODE_MODULE;
