import vscode from "vscode";

import protocol from "./protocol";

const env: typeof vscode.env = {
  openExternal: async (target) => {
    const msg = await protocol.sendMessage("env", "openExternal", [
      target.toString(true),
    ]);
    // True or false
    return msg.args[0];
  },
  asExternalUri: undefined,
  appName: "",
  appRoot: "",
  appHost: "",
  uriScheme: "",
  language: "",
  clipboard: undefined,
  machineId: "",
  sessionId: "",
  isNewAppInstall: false,
  isTelemetryEnabled: false,
  onDidChangeTelemetryEnabled: undefined,
  remoteName: undefined,
  shell: "",
  uiKind: vscode.UIKind.Desktop,
  logLevel: vscode.LogLevel.Off,
  onDidChangeLogLevel: undefined,
};
const commands: typeof vscode.commands = {
  registerCommand: undefined,
  registerTextEditorCommand: undefined,
  executeCommand: undefined,
  getCommands: undefined,
};
const workspace: typeof vscode.workspace = {
  getWorkspaceFolder: undefined,
  asRelativePath: undefined,
  updateWorkspaceFolders: undefined,
  createFileSystemWatcher: undefined,
  findFiles: undefined,
  saveAll: undefined,
  applyEdit: undefined,
  openTextDocument: undefined,
  registerTextDocumentContentProvider: undefined,
  openNotebookDocument: undefined,
  registerNotebookSerializer: undefined,
  getConfiguration: undefined,
  registerTaskProvider: undefined,
  registerFileSystemProvider: undefined,
  fs: undefined,
  rootPath: undefined,
  workspaceFolders: undefined,
  name: undefined,
  workspaceFile: undefined,
  onDidChangeWorkspaceFolders: undefined,
  textDocuments: [],
  onDidOpenTextDocument: undefined,
  onDidCloseTextDocument: undefined,
  onDidChangeTextDocument: undefined,
  onWillSaveTextDocument: undefined,
  onDidSaveTextDocument: undefined,
  notebookDocuments: [],
  onDidChangeNotebookDocument: undefined,
  onDidSaveNotebookDocument: undefined,
  onDidOpenNotebookDocument: undefined,
  onDidCloseNotebookDocument: undefined,
  onWillCreateFiles: undefined,
  onDidCreateFiles: undefined,
  onWillDeleteFiles: undefined,
  onDidDeleteFiles: undefined,
  onWillRenameFiles: undefined,
  onDidRenameFiles: undefined,
  onDidChangeConfiguration: undefined,
  isTrusted: false,
  onDidGrantWorkspaceTrust: undefined,
};
const window: typeof vscode.window = {
  showTextDocument: undefined,
  showNotebookDocument: undefined,
  createTextEditorDecorationType: undefined,
  showInformationMessage: undefined,
  showWarningMessage: undefined,
  showErrorMessage: undefined,
  showQuickPick: undefined,
  showWorkspaceFolderPick: undefined,
  showOpenDialog: undefined,
  showSaveDialog: undefined,
  showInputBox: undefined,
  createQuickPick: undefined,
  createInputBox: undefined,
  createOutputChannel: undefined,
  createWebviewPanel: undefined,
  setStatusBarMessage: undefined,
  withScmProgress: undefined,
  withProgress: undefined,
  createStatusBarItem: undefined,
  createTerminal: undefined,
  registerTreeDataProvider: undefined,
  createTreeView: undefined,
  registerUriHandler: undefined,
  registerWebviewPanelSerializer: undefined,
  registerWebviewViewProvider: undefined,
  registerCustomEditorProvider: undefined,
  registerTerminalLinkProvider: undefined,
  registerTerminalProfileProvider: undefined,
  registerFileDecorationProvider: undefined,
  tabGroups: undefined,
  activeTextEditor: undefined,
  visibleTextEditors: [],
  onDidChangeActiveTextEditor: undefined,
  onDidChangeVisibleTextEditors: undefined,
  onDidChangeTextEditorSelection: undefined,
  onDidChangeTextEditorVisibleRanges: undefined,
  onDidChangeTextEditorOptions: undefined,
  onDidChangeTextEditorViewColumn: undefined,
  visibleNotebookEditors: [],
  onDidChangeVisibleNotebookEditors: undefined,
  activeNotebookEditor: undefined,
  onDidChangeActiveNotebookEditor: undefined,
  onDidChangeNotebookEditorSelection: undefined,
  onDidChangeNotebookEditorVisibleRanges: undefined,
  terminals: [],
  activeTerminal: undefined,
  onDidChangeActiveTerminal: undefined,
  onDidOpenTerminal: undefined,
  onDidCloseTerminal: undefined,
  onDidChangeTerminalState: undefined,
  state: undefined,
  onDidChangeWindowState: undefined,
  activeColorTheme: undefined,
  onDidChangeActiveColorTheme: undefined,
};
const authentication: typeof vscode.authentication = {
  getSession: undefined,
  registerAuthenticationProvider: undefined,
  onDidChangeSessions: undefined,
};
const comments: typeof vscode.comments = {
  createCommentController: undefined,
};
const debug: typeof vscode.debug = {
  registerDebugConfigurationProvider: undefined,
  registerDebugAdapterDescriptorFactory: undefined,
  registerDebugAdapterTrackerFactory: undefined,
  startDebugging: undefined,
  stopDebugging: undefined,
  addBreakpoints: undefined,
  removeBreakpoints: undefined,
  asDebugSourceUri: undefined,
  activeDebugSession: undefined,
  activeDebugConsole: undefined,
  breakpoints: [],
  onDidChangeActiveDebugSession: undefined,
  onDidStartDebugSession: undefined,
  onDidReceiveDebugSessionCustomEvent: undefined,
  onDidTerminateDebugSession: undefined,
  onDidChangeBreakpoints: undefined,
};
const extensions: typeof vscode.extensions = {
  getExtension: undefined,
  all: [],
  onDidChange: undefined,
};
const tasks: typeof vscode.tasks = {
  registerTaskProvider: undefined,
  fetchTasks: undefined,
  executeTask: undefined,
  taskExecutions: [],
  onDidStartTask: undefined,
  onDidEndTask: undefined,
  onDidStartTaskProcess: undefined,
  onDidEndTaskProcess: undefined,
};
const l10n: typeof vscode.l10n = {
  t: undefined,
  bundle: undefined,
  uri: undefined,
};
const languages: typeof vscode.languages = {
  getLanguages: undefined,
  setTextDocumentLanguage: undefined,
  match: undefined,
  getDiagnostics: undefined,
  createDiagnosticCollection: undefined,
  createLanguageStatusItem: undefined,
  registerCompletionItemProvider: undefined,
  registerInlineCompletionItemProvider: undefined,
  registerCodeActionsProvider: undefined,
  registerCodeLensProvider: undefined,
  registerDefinitionProvider: undefined,
  registerImplementationProvider: undefined,
  registerTypeDefinitionProvider: undefined,
  registerDeclarationProvider: undefined,
  registerHoverProvider: undefined,
  registerEvaluatableExpressionProvider: undefined,
  registerInlineValuesProvider: undefined,
  registerDocumentHighlightProvider: undefined,
  registerDocumentSymbolProvider: undefined,
  registerWorkspaceSymbolProvider: undefined,
  registerReferenceProvider: undefined,
  registerRenameProvider: undefined,
  registerDocumentSemanticTokensProvider: undefined,
  registerDocumentRangeSemanticTokensProvider: undefined,
  registerDocumentFormattingEditProvider: undefined,
  registerDocumentRangeFormattingEditProvider: undefined,
  registerOnTypeFormattingEditProvider: undefined,
  registerSignatureHelpProvider: undefined,
  registerDocumentLinkProvider: undefined,
  registerColorProvider: undefined,
  registerInlayHintsProvider: undefined,
  registerFoldingRangeProvider: undefined,
  registerSelectionRangeProvider: undefined,
  registerCallHierarchyProvider: undefined,
  registerTypeHierarchyProvider: undefined,
  registerLinkedEditingRangeProvider: undefined,
  registerDocumentDropEditProvider: undefined,
  setLanguageConfiguration: undefined,
  onDidChangeDiagnostics: undefined,
};
const notebooks: typeof vscode.notebooks = {
  createNotebookController: undefined,
  registerNotebookCellStatusBarItemProvider: undefined,
  createRendererMessaging: undefined,
};
const scm: typeof vscode.scm = {
  createSourceControl: undefined,
  inputBox: undefined,
};
const tests: typeof vscode.tests = {
  createTestController: undefined,
};

const VSCODE_MODULE: typeof vscode = {
  version: vscode.version,
  // namespaces
  env,
  authentication,
  commands,
  comments,
  debug,
  extensions,
  l10n,
  languages,
  notebooks,
  scm,
  tasks,
  tests,
  window,
  workspace,
  // types
  Position: undefined,
  Range: undefined,
  Selection: undefined,
  TextEditorSelectionChangeKind: undefined,
  TextEditorCursorStyle: undefined,
  TextEditorLineNumbersStyle: undefined,
  TextEditorRevealType: undefined,
  OverviewRulerLane: undefined,
  DecorationRangeBehavior: undefined,
  ThemeColor: undefined,
  ThemeIcon: undefined,
  EndOfLine: undefined,
  Uri: undefined,
  CancellationTokenSource: undefined,
  CancellationError: undefined,
  Disposable: undefined,
  EventEmitter: undefined,
  QuickPickItemKind: undefined,
  InputBoxValidationSeverity: undefined,
  RelativePattern: undefined,
  CodeActionKind: undefined,
  CodeActionTriggerKind: undefined,
  CodeAction: undefined,
  CodeLens: undefined,
  MarkdownString: undefined,
  Hover: undefined,
  EvaluatableExpression: undefined,
  InlineValueText: undefined,
  InlineValueVariableLookup: undefined,
  InlineValueEvaluatableExpression: undefined,
  DocumentHighlightKind: undefined,
  DocumentHighlight: undefined,
  SymbolKind: undefined,
  SymbolTag: undefined,
  SymbolInformation: undefined,
  DocumentSymbol: undefined,
  TextEdit: undefined,
  SnippetTextEdit: undefined,
  NotebookEdit: undefined,
  WorkspaceEdit: undefined,
  SnippetString: undefined,
  SemanticTokensLegend: undefined,
  SemanticTokensBuilder: undefined,
  SemanticTokens: undefined,
  SemanticTokensEdits: undefined,
  SemanticTokensEdit: undefined,
  ParameterInformation: undefined,
  SignatureInformation: undefined,
  SignatureHelp: undefined,
  SignatureHelpTriggerKind: undefined,
  CompletionItemKind: undefined,
  CompletionItemTag: undefined,
  CompletionItem: undefined,
  CompletionList: undefined,
  CompletionTriggerKind: undefined,
  InlineCompletionList: undefined,
  InlineCompletionTriggerKind: undefined,
  InlineCompletionItem: undefined,
  DocumentLink: undefined,
  Color: undefined,
  ColorInformation: undefined,
  ColorPresentation: undefined,
  InlayHintKind: undefined,
  InlayHintLabelPart: undefined,
  InlayHint: undefined,
  FoldingRange: undefined,
  FoldingRangeKind: undefined,
  SelectionRange: undefined,
  CallHierarchyItem: undefined,
  CallHierarchyIncomingCall: undefined,
  CallHierarchyOutgoingCall: undefined,
  TypeHierarchyItem: undefined,
  LinkedEditingRanges: undefined,
  DocumentDropEdit: undefined,
  IndentAction: undefined,
  ConfigurationTarget: undefined,
  Location: undefined,
  DiagnosticSeverity: undefined,
  DiagnosticRelatedInformation: undefined,
  DiagnosticTag: undefined,
  Diagnostic: undefined,
  LanguageStatusSeverity: undefined,
  ViewColumn: undefined,
  StatusBarAlignment: undefined,
  TerminalLocation: undefined,
  TerminalLink: undefined,
  TerminalProfile: undefined,
  FileDecoration: undefined,
  ExtensionKind: undefined,
  ExtensionMode: undefined,
  ColorThemeKind: undefined,
  TaskRevealKind: undefined,
  TaskPanelKind: undefined,
  TaskGroup: undefined,
  ProcessExecution: undefined,
  ShellQuoting: undefined,
  ShellExecution: undefined,
  CustomExecution: undefined,
  TaskScope: undefined,
  Task: undefined,
  FileType: undefined,
  FilePermission: undefined,
  FileSystemError: undefined,
  FileChangeType: undefined,
  UIKind: undefined,
  LogLevel: undefined,
  DataTransferItem: undefined,
  DataTransfer: undefined,
  TreeItem: undefined,
  TreeItemCollapsibleState: undefined,
  TerminalExitReason: undefined,
  EnvironmentVariableMutatorType: undefined,
  ProgressLocation: undefined,
  QuickInputButtons: undefined,
  TextDocumentChangeReason: undefined,
  TextDocumentSaveReason: undefined,
  NotebookEditorRevealType: undefined,
  NotebookCellKind: undefined,
  NotebookRange: undefined,
  NotebookCellOutputItem: undefined,
  NotebookCellOutput: undefined,
  NotebookCellData: undefined,
  NotebookData: undefined,
  NotebookControllerAffinity: undefined,
  NotebookCellStatusBarAlignment: undefined,
  NotebookCellStatusBarItem: undefined,
  DebugAdapterExecutable: undefined,
  DebugAdapterServer: undefined,
  DebugAdapterNamedPipeServer: undefined,
  DebugAdapterInlineImplementation: undefined,
  Breakpoint: undefined,
  SourceBreakpoint: undefined,
  FunctionBreakpoint: undefined,
  DebugConsoleMode: undefined,
  DebugConfigurationProviderTriggerKind: undefined,
  CommentThreadCollapsibleState: undefined,
  CommentMode: undefined,
  TestRunProfileKind: undefined,
  TestTag: undefined,
  TestRunRequest: undefined,
  TestMessage: undefined,
  TabInputText: undefined,
  TabInputTextDiff: undefined,
  TabInputCustom: undefined,
  TabInputWebview: undefined,
  TabInputNotebook: undefined,
  TabInputNotebookDiff: undefined,
  TabInputTerminal: undefined,
};

export default VSCODE_MODULE;
